spring:
    application:
        name: drello
    profiles:
        active: prod
    data:
        rest:
          base-path: /api
    main:
        banner-mode: "off"
    jpa:
        show_sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
    mvc:
        favicon:
            enabled: false
---
spring:
    profiles: dev
    datasource:
      url: jdbc:postgresql://localhost:5432/drello-postgr
      username: oleg
      password:
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
    resources:
        chain:
            cache: false
---
spring:
    profiles: test
    datasource:
      url: jdbc:h2:~/mydb;DB_CLOSE_ON_EXIT=FALSE
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
      dbcp:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    resources:
        chain:
            cache: false
---
spring:
    profiles: prod
    datasource:
      url: jdbc:postgresql://ec2-54-75-249-162.eu-west-1.compute.amazonaws.com:5432/d9cjmp912t28h1
      username: ypoaivwtamtvuv
      password: e6dd668f830e2390f9eafef029334d46b2333569b98100717e670b5b2382b94c
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    resources:
        chain:
            cache: false